### ISSUE TITLE
An Social account does not show

### ISSUE THREAD

**Issue by worapots** [yrchen/CommonRepo#2]
### Expected behavior

a Social account shows after update My Social Account.
### Actual behavior

a Google Plus account does not show in user profile page, socials information
### Steps to reproduce the behavior

1.Click on "update my social account" button in user profile page.
2. Add a 3rd party account.
3. Visit a user profile page.

**Comment by yrchen** [comment]
@TitleUpz OK, I think it's a feature that I have not implement yet. I will fix this in next major release version v1.1.x. Thanks. :+1:
